### ISSUE TITLE
[Windows 10] Error when entering playlist URL

### ISSUE THREAD

**Issue by PassiveLemon** [casualsnek/onthespot#10]
```
URL download clicked with value False
Parsing url 'False'
Uncaught exception
Traceback (most recent call last):
  File "onthespot.py", line 559, in __download_by_url
  File "utils.py", line 172, in get_url_data
  File "utils.py", line 86, in regex_input_for_urls
  File "re.py", line 200, in search
TypeError: expected string or bytes-like object
```
I don't know python so I can't make much sense of this.

**Comment by PassiveLemon** [comment]
Also, do you think its possible that you could make the windows an "installer" type executable which makes a folder in the directory of the exe which will then automatically download ffmpeg and use that path?

**Comment by casualsnek** [comment]
> Also, do you think its possible that you could make the windows an "installer" type executable which makes a folder in the directory of the exe which will then automatically download ffmpeg and use that path?

I haved pushed commits that should fix this issue, and i also noticed windows having various issues like missing ffmpeg and stuck on 99% with permission error. The build scripts have changed and need documentation to run from source. Meanwhile can you try this binary release built against current main branch: https://anonfiles.com/69zbldBey8/onthespot_win_exe

This also comes with it's own ffmpeg so no installer required !

**Comment by PassiveLemon** [comment]
Seems to work well. Cool. My issue has been solved. Thanks
