### ISSUE TITLE
[Feature] Metadata options

### ISSUE THREAD

**Issue by Edison12300** [casualsnek/onthespot#100]
Can you add an option to change it to , for multiple artists instead of ;?
Also is their a way to keep it from adding the id in the comment?
Thanks!

**Comment by casualsnek** [comment]
> Can you add an option to change it to , for multiple artists instead of ;? Also is their a way to keep it from adding the id in the comment? Thanks!

For the separator, it's configurable by editing config even though it'd option is not in UI yet, open config file with a text editor and edit value of ``metadata_seperator`` key !
ID(s) in comment field needs change in code itself and is not user configurable. I will add option to configure what metadata will be written in future version !

**Comment by Edison12300** [comment]
I did try to change the config, not sure if it is the right one though.
I change the line in onthespot\src\onthespot\otsconfig.py to "metadata_seperator": ",", but it still ouputs with the semicolon.

**Comment by Edison12300** [comment]
Also, forgot to ask is there is a way to just have the disk and track number to just output how much it is?
Currently it outputs with a /total.
