### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by JericoFX** [casualsnek/onthespot#14]
![image](https://user-images.githubusercontent.com/56100605/194439306-a88fc5b9-073c-497f-8948-b2b4c975c4f8.png)

Hi, first of all awesome program, when i try to download something this pop on console

**Comment by casualsnek** [comment]
The URL seems to work fine for me, can you try again ? Maybe it's a temporary issue !

**Comment by JericoFX** [comment]
Hi, the error persist but at leas i know is on my end, i appreciate the help

**Comment by casualsnek** [comment]
> 

By the way can you search for the song and then download it from search results and see if works or not ?
