### ISSUE TITLE
[BUG] I Was Wrong.

### ISSUE THREAD

**Issue by MonkeyDLuffy-Gang** [casualsnek/onthespot#160]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. iOS, Windows 11]
 - OnTheSpot Version: [e.g. 0.4]

**Additional context**

**Comment by sys-admn-ploopy** [comment]
Hi! This bug is currently due to a long standing issue with an upstream service. 
Please see #144 for more details!

here is a link to a comment with the best current solution: https://github.com/casualsnek/onthespot/issues/144#issuecomment-2292409458.
