### ISSUE TITLE
[Feature Request] Change titles of downloaded content based on data.

### ISSUE THREAD

**Issue by PassiveLemon** [casualsnek/onthespot#2]
So rather than having it be shown by `author - album - ##.song name`, add a feature to be able to change what the title of the mp3 but still have song metadata in the mp3. This could just be an option in a preference menu

Ex:
Currently: `The Cranberries - No Need To Argue (The Complete Sessions 1994-1995) - 04. Zombie.mp3`
What I would like: `Zombie.mp3`

**Comment by casualsnek** [comment]
Thanks for feedback, i plan on adding advanced option to specify track name formats and album directories format !

**Comment by casualsnek** [comment]
> So rather than having it be shown by `author - album - ##.song name`, add a feature to be able to change what the title of the mp3 but still have song metadata in the mp3. This could just be an option in a preference menu
> 
> Ex: Currently: `The Cranberries - No Need To Argue (The Complete Sessions 1994-1995) - 04. Zombie.mp3` What I would like: `Zombie.mp3`

Can you please check the latest commit. I have added the option for it. You need to click show advanced setting and use the variables as specified in the README.md

**Comment by PassiveLemon** [comment]
Works great. Thank you!
