### ISSUE TITLE
Blurry Album Art

### ISSUE THREAD

**Issue by SkyWishbringer** [casualsnek/onthespot#20]
The album art is blurry now when I download albums. I checked back with the previous version and the blurry art is still there sadly. I also checked maybe downloading a new album would display clear album art, but they are affected as well. Then I tried resetting everything and tried again, still blurry. I can just replace the album art, but I figured I'd post here.

**Comment by casualsnek** [comment]
I have found the issue and fix for it, i will push a larger update with UI improvements and few other bugfixes including this soon !

-------- Original Message --------

**Comment by whoisYoges** [comment]
@casualsnek how about adding an icon to the project as well, so that i could make a desktop entry for linux to launch `onthespot` from application launcher?

**Comment by whoisYoges** [comment]
And dark mode as well?

**Comment by casualsnek** [comment]
> And dark mode as well?

I will try making a icon for application as well.

For dark mode it follows system Qt style. I am on Plasma desktop and it follows my system color scheme. [Screenshot](https://i.imgur.com/AqdA892.png)
I have to see how to get it to look good on non plasma desktops !

**Comment by whoisYoges** [comment]
> > And dark mode as well?
> 
> I will try making a icon for application as well.
> 
> For dark mode it follows system Qt style. I am on Plasma desktop and it follows my system color scheme. [Screenshot](https://i.imgur.com/AqdA892.png) I have to see how to get it to look good on non plasma desktops !

I'm using DWM and yeah i can see the difference. I guess in app dark-white mode switch option would be better if possible for non qt users.

![Screenshot: white ui in dark theme](https://user-images.githubusercontent.com/51807726/196035067-371d6659-8738-461b-b2f7-e1504b17ce34.png)
