### ISSUE TITLE
feature: adding file naming formatting for songs

### ISSUE THREAD

**Issue by calvin-li-developer** [casualsnek/onthespot#25]
currently in the advance settings you can add {track_number} {name}. Is it possible to make it 0{track_number} {name} ? 

example: 
- current: 4 Bad Habits

- request: 04 Bad Habits 

this should also be changed for the lrc files.

**Comment by casualsnek** [comment]
You should be able to do that with no issue, but if you use 0{track_number} it will use 010 if you go over 9th track.

**Comment by calvin-li-developer** [comment]
is there any to format it so that it always have 2 digit placement for songs? I understand you're method works for single digit track number but it would be great if there's option for this.

**Comment by casualsnek** [comment]
> is there any to format it so that it always have 2 digit placement for songs? I understand you're method works for single digit track number but it would be great if there's option for this.

can you try ```{track_number:0>2d}``` and see if it works ? This should work as you expect! You can refer to python fstring formats for more !

You may close the issue if this does what you want !
