### ISSUE TITLE
[Bug] Destination directory was moved and now everything is locked

### ISSUE THREAD

**Issue by gummykage** [casualsnek/onthespot#33]
Where is the configuration stored? How do I fix this? I'm a noob to python. Thank you in advanced. m( _ _)m

![image](https://user-images.githubusercontent.com/9695713/201622322-5139d5ad-4daf-4e78-9332-73bea48315bd.png)

**Comment by casualsnek** [comment]
> Where is the configuration stored? How do I fix this? I'm a noob to python. Thank you in advanced. m( _ _)m
> 
> ![image](https://user-images.githubusercontent.com/9695713/201622322-5139d5ad-4daf-4e78-9332-73bea48315bd.png)

You should be able to find config file at ```C:\Users\<username>\.config\casualonthespot\```
Thanks for finding the issue, i will add fallback path as well as check if path is valid before config is saved !

**Comment by gummykage** [comment]
Thank you so much @casualsnek . m(_ _)m
