### ISSUE TITLE
High quality art

### ISSUE THREAD

**Issue by MrAvana** [casualsnek/onthespot#41]
Is it possible to get higher quality art (album covers)? The current resolution is too low and looks blurry on most media players.

**Comment by casualsnek** [comment]
> Is it possible to get higher quality art (album covers)? The current resolution is too low and looks blurry on most media players.

Have you tried using master or development branch. The issues should be be fixed on it !

**Comment by MrAvana** [comment]
I tried the development branch but the art is still blurry (low quality).

**Comment by casualsnek** [comment]
> I tried the development branch but the art is still blurry (low quality).

Looks like something has changed again, i will push a fix on main asap !

**Comment by MrAvana** [comment]
Thank you very much!

**Comment by jimboso** [comment]
The high quality art is still working on your windows v0.4 release.  This might help point you in the correct direction for a fix.

Also, there are some other issues.  When checking the ID3 tag, the artwork image has the name "image/none".  Many programs can process the file extension, but there are some that will not.   It would be better if it was being named to "image/jpeg".  I am not sure what is controlling this.

Great program btw!

**Comment by MrAvana** [comment]
NB. I'm using 0.4 on Pop OS.

**Comment by casualsnek** [comment]
Can you check the latest development branch ? The issues should be fixed now !
