### ISSUE TITLE
Feature: Add to album directory name formatter a parameter {playlist}

### ISSUE THREAD

**Issue by p-angelov** [casualsnek/onthespot#43]
I miss the feature when downloading a playlist to download all song to a folder named after the playlist

**Comment by casualsnek** [comment]
> I miss the feature when downloading a playlist to download all song to a folder named after the playlist

Thanks for feedback, i designed this tool to use m3u files for playlists as it would avoid downloading same some multiple times if they are in different playlists.

But i will add a option to define playlist directories for users that do not have issue with duplicate files. The feature itself should be fairly easy to add :)

**Comment by casualsnek** [comment]
Can you try the development branch ! You can use 'playlist_name', 'playlist_owner' and 'playlist_desc' formatter. It will be replaced with playlist info if the current media is part of a playlist !
