### ISSUE TITLE
Feature: Read links from playlist

### ISSUE THREAD

**Issue by nicfitzgerald** [casualsnek/onthespot#46]
There are other media downloaders, [Gallery-DL](https://github.com/mikf/gallery-dl) and [YT DLP](https://github.com/yt-dlp/yt-dlp), that can take a text document of links and use that as a download source. Since the GUI already takes in the download, it sounds like it may be possible to use that to read from a list of links.

**Comment by nicfitzgerald** [comment]
Apologies - it looks like there was a UI overhaul between the prebuilt binaries and the source. It may be slightly harder to get this feature implemented now.

**Comment by casualsnek** [comment]
I think it's doable, i may make it so that it can take path to txt file as url or text file could be dragged and dropped into url/search field, then parse it for downloading !

**Comment by nicfitzgerald** [comment]
The path to a text file as the URL would be super great, from a user standpoint.

**Comment by casualsnek** [comment]
> The path to a text file as the URL would be super great, from a user standpoint.

The latest development branch should support this ! Can you check if it's working ?

**Comment by nicfitzgerald** [comment]
I will pull it and test right now!
