### ISSUE TITLE
Stuck at 99% - PermissionError

### ISSUE THREAD

**Issue by dylanrsmith** [casualsnek/onthespot#5]
Was getting this error when downloading a track.

Progress bar would be stuck 'converting' at 99%.

Not sure if this is a widespread issue, I think I found a potential fix.

```
Traceback (most recent call last):
  File "spotutils.py", line 394, in run
    status = self.download_track(
  File "spotutils.py", line 328, in download_track
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Music/Song.mp3'
```

**Comment by Miollnir** [comment]
i have the same issue
did u found a fix ?

**Comment by Ragriod** [comment]
![image](https://user-images.githubusercontent.com/25598754/193723850-02cd6730-17c9-49b8-9f42-1d28485f34a4.png)

After download the track is stuck with converting at 99%

**Comment by casualsnek** [comment]
> i have the same issue did u found a fix ?

Maybe yes, i will push a commit in a while which you can test !

**Comment by casualsnek** [comment]
> ![image](https://user-images.githubusercontent.com/25598754/193723850-02cd6730-17c9-49b8-9f42-1d28485f34a4.png)
> 
> After download the track is stuck with converting at 99%

Can you test it now ? I have binary release for windows which you can use ! Also follow ```Installing on windows``` section in README.md to install ffmpeg which should solve these issues

**Comment by Miollnir** [comment]
> Can you test it now ? I have binary release for windows which you can use ! Also follow `Installing on windows` section in README.md to install ffmpeg which should solve these issues

it works now 👍

**Comment by casualsnek** [comment]
> Was getting this error when downloading a track.
> 
> Progress bar would be stuck 'converting' at 99%.
> 
> Not sure if this is a widespread issue, I think I found a potential fix.
> 
> ```
> Traceback (most recent call last):
>   File "spotutils.py", line 394, in run
>     status = self.download_track(
>   File "spotutils.py", line 328, in download_track
>     os.remove(filename)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Music/Song.mp3'
> ```

Can you please test this binary release: https://anonfiles.com/69zbldBey8/onthespot_win_exe  built against current main branch !
Apparently there were multiple reasons why this could happen and this binary should work as expected. The build instructions and scripts were changed so while i write documentation on it you can try the binary and check if it works !

**Comment by dylanrsmith** [comment]
Just tested that binary and it works ! I'll close this issue. Thanks!
