### ISSUE TITLE
Login failed, probably invalid username or password

### ISSUE THREAD

**Issue by BlueCalex** [casualsnek/onthespot#57]
After working for a while, i recently reinstalled as i lost the original EXE

My login isnt working, despite my creds being 100% correct, (tested, even copied/pasted)

Tried clearing my .cache/onthespot folder, still doesnt work. Is there any other cache / temp folders i can delete, as it still remembers my old Directory so something is still there

OUTPUT:

**gui\mainui.py -> 549:       __add_account() :: ERROR] -> Account add failed for : ACCOUNTNAME**

Thanks in advance

**Comment by sadboolean** [comment]
Same here...worked a couple of days ago and when I went to use just now, kept getting invalid credentials and had to clear the cache just to get to launch but nothing...in a bind, really need to use by Thursday! :(

**Comment by sadboolean** [comment]
Tried making and logging in with a new spotify account...nada...shows invalid credentials, so something is up

**Comment by casualsnek** [comment]
I'll have a look at that issue, maybe something to do with librespot-python library !

**Comment by sadboolean** [comment]
> 

thank you so much! <3

**Comment by casualsnek** [comment]
Probably this: https://github.com/kokarare1212/librespot-python/issues/193

**Comment by sadboolean** [comment]
> Probably this: [kokarare1212/librespot-python#193](https://github.com/kokarare1212/librespot-python/issues/193)

Sorry not too informed with the topic, does this mean it's no longer possible due to changes on Spotify's end?

**Comment by casualsnek** [comment]
> > Probably this: [kokarare1212/librespot-python#193](https://github.com/kokarare1212/librespot-python/issues/193)
> 
> Sorry not too informed with the topic, does this mean it's no longer possible due to changes on Spotify's end?

The fix is already there, i'll probably wait until it's fixed in librespot-python itself. If you are willing to get it working before fix is merged, ping me on discord !

**Comment by sadboolean** [comment]
> > > Probably this: [kokarare1212/librespot-python#193](https://github.com/kokarare1212/librespot-python/issues/193)
> > 
> > 
> > Sorry not too informed with the topic, does this mean it's no longer possible due to changes on Spotify's end?
> 
> The fix is already there, i'll probably wait until it's fixed in librespot-python itself. If you are willing to get it working before fix is merged, ping me on discord !

tried to click on discord link in your profile but says expired, let me know!

**Comment by casualsnek** [comment]
> > > > Probably this: [kokarare1212/librespot-python#193](https://github.com/kokarare1212/librespot-python/issues/193)
> > > 
> > > 
> > > Sorry not too informed with the topic, does this mean it's no longer possible due to changes on Spotify's end?
> > 
> > 
> > The fix is already there, i'll probably wait until it's fixed in librespot-python itself. If you are willing to get it working before fix is merged, ping me on discord !
> 
> tried to click on discord link in your profile but says expired, let me know!

Try this : https://discord.gg/g9c4RgXP

**Comment by sadboolean** [comment]
> > > > > Probably this: [kokarare1212/librespot-python#193](https://github.com/kokarare1212/librespot-python/issues/193)
> > > > 
> > > > 
> > > > Sorry not too informed with the topic, does this mean it's no longer possible due to changes on Spotify's end?
> > > 
> > > 
> > > The fix is already there, i'll probably wait until it's fixed in librespot-python itself. If you are willing to get it working before fix is merged, ping me on discord !
> > 
> > 
> > tried to click on discord link in your profile but says expired, let me know!
> 
> Try this : https://discord.gg/g9c4RgXP

back and better than ever, thanks so much!

**Comment by 80-am** [comment]
This issue can be solved by bumping librespot to 0.0.9.

I have created a [pull request](https://github.com/casualsnek/onthespot/pull/58).

Thank you for this project!

**Comment by Superporff2000** [comment]
I am facing issues with logging in as well. It says
`Failed logging in user <user>, invalid credentials`
and
```
  File "worker\session.py", line 28, in run
TypeError: 'NoneType' object is not subscriptable
```

**Comment by casualsnek** [comment]
> I am facing issues with logging in as well. It says
> 
> ```
> Failed logging in user <user>, invalid credentials
> ```
> 
> and
> 
> ```
>   File "worker\session.py", line 28, in run
> TypeError: 'NoneType' object is not subscriptable
> ```

Due to recent changes, the last binary version won't again ! There are builds from development branch that you can use in discord ! If you are not on discord i can share it here too !

**Comment by r926215** [comment]
> > I am facing issues with logging in as well. It says
> > ```
> > Failed logging in user <user>, invalid credentials
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> >   File "worker\session.py", line 28, in run
> > TypeError: 'NoneType' object is not subscriptable
> > ```
> 
> Due to recent changes, the last binary version won't again ! There are builds from development branch that you can use in discord ! If you are not on discord i can share it here too !

can you repost the discord invitation link? The old one expired

**Comment by juggernaut451451** [comment]
> > > I am facing issues with logging in as well. It says
> > > ```
> > > Failed logging in user <user>, invalid credentials
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and
> > > ```
> > >   File "worker\session.py", line 28, in run
> > > TypeError: 'NoneType' object is not subscriptable
> > > ```
> > 
> > 
> > Due to recent changes, the last binary version won't again ! There are builds from development branch that you can use in discord ! If you are not on discord i can share it here too !
> 
> can you repost the discord invitation link? The old one expired

Seconding this, I would need a recent discord link to get a dev build from you. Thank you in advance.

**Comment by casualsnek** [comment]
> > > > I am facing issues with logging in as well. It says
> > > > ```
> > > > Failed logging in user <user>, invalid credentials
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and
> > > > ```
> > > >   File "worker\session.py", line 28, in run
> > > > TypeError: 'NoneType' object is not subscriptable
> > > > ```
> > > 
> > > 
> > > Due to recent changes, the last binary version won't again ! There are builds from development branch that you can use in discord ! If you are not on discord i can share it here too !
> > 
> > 
> > can you repost the discord invitation link? The old one expired
> 
> Seconding this, I would need a recent discord link to get a dev build from you. Thank you in advance.

This should be a valid invite url: https://discord.gg/MB2u8Z6mxS
