### ISSUE TITLE
"'Cp932' codec can't decode" occurs on Japanese OS

### ISSUE THREAD

**Issue by ghost** [casualsnek/onthespot#59]
Add encoding='UTF-8' utility.py to resolve'cp932' codec can't decode

with open(playlist_m3u_queue[play_id]['filename'], 'w')
to
with open(playlist_m3u_queue[play_id]['filename'], 'w', encoding='UTF-8')

and

with open(playlist_m3u_queue[play_id]['filename'], 'a')
to
with open(playlist_m3u_queue[play_id]['filename'], 'a', encoding='UTF-8')

I'm not sure how to do pull requests, so I'm going to write to ISSUES
Sorry.

**Comment by casualsnek** [comment]
Thanks for reporting the issue ! It should fixed now after this https://github.com/casualsnek/onthespot/commit/77632bb5fd349b92308a1eed9113d7b9f58d3329

**Comment by ghost** [comment]
i forgot to reply
It was fixed too.
thank you
