### ISSUE TITLE
Incorrect download location upon changing location

### ISSUE THREAD

**Issue by skrubbybubby** [casualsnek/onthespot#61]
Using the latest version from your discord server, on Windows 10

Manually selecting a download location uses `/` instead of `\` for subdirectory locations, which are removed in the console leading to constant "No such file or directory" when trying to download (given you have saved your changes). 
An example is choosing `C:\Users\Username\Desktop\OnTheSpot` being changed to `C:UsersUsernameDesktopOnTheSpot`. 
This issue also occurs when I change the slash in "Album directory name formatter" under Advanced configuration from `\` to `/` and persists after restarting. 
![image](https://github.com/casualsnek/onthespot/assets/124408406/8b5239d3-27ad-4819-ad19-7c296edf7b96)

Additionally when you click on Browse to select a location but instead cancel (or x), the download location text in the bar is removed, despite not resetting the download location. The popup selection defaults to your user folder instead whether or not a change has been made to the download location.
_For some reason this fixes the above issue while saving in the same location._

Other than the issue above, I don't think it's because of my upscaling on my laptop but the location bar is very short. Could it instead use the space underneath to display a much longer path? ![image](https://github.com/casualsnek/onthespot/assets/124408406/1982feb9-b80a-4653-9018-5b2c630318ad)

Thanks for your work,
skrubbybubby
P.S. sorry if I forgot anything this is my first github issue report

**Comment by casualsnek** [comment]
Thanks for reporting issue ! The path separator issue is fixed now as Qt file browser returned incorrect separator in windows. For the path getting cleared if cancelled, I'll fix that right now.

EDIT: Should be fixed now in development branch !
Changes to interface will probably done on next version as the code handling UI needs cleanup too !

**Comment by skrubbybubby** [comment]
Alright thanks for the reply, it's not a big issue and I'll wait for the new release
