### ISSUE TITLE
[BUG] Cancelled downloads don't clear when clicking "clear completed/cancelled items"

### ISSUE THREAD

**Issue by TheZachAttack01** [casualsnek/onthespot#71]
downloads that were cancelled in the progress tab don't go away unless the program is restarted. clicking the "clear completed/cancelled items" button at the bottom only removed finished downloads, not cancelled ones.

I'm using the latest build on arch linux

**Comment by casualsnek** [comment]
This should be fixed now ! If you are using AUR, force a rebuild, this should update your installed version !

**Comment by TheZachAttack01** [comment]
That worked! Thanks for the quick response!
