### ISSUE TITLE
Not downloading new songs added to a Playlist on Spotify

### ISSUE THREAD

**Issue by OrigWhiteKenyan** [casualsnek/onthespot#74]
I've had the issue where I've added additional songs to a playlist on Spotify and then have created folders inside of the OnTheSpot directory for them. I switched the download directory to the corresponding playlist folder and reload the playlist into OnTheSpot so it will register the already downloaded songs and only download the new ones. However, it just shows all downloads as complete and doesn't have the additional 50 or so songs I've added since the last time I downloaded the playlist.

**Comment by casualsnek** [comment]
This seems to be cache issue to me ! Can you try deleting ```/home/<username>/.cache/casualOnTheSpot/reqcache``` directory if you are on linux or ```C:\Users\<username\.cache\casualOnTheSpot\reqcache``` if you are on windows and see if playlist shows new items !

**Comment by OrigWhiteKenyan** [comment]
That did the trick. Thank you!

**Comment by casualsnek** [comment]
> That did the trick. Thank you!

I just pushed an update, https://github.com/casualsnek/onthespot/pull/96 should fix this issue, if you want i can build a new binary, and this should be included in next update !
