### ISSUE TITLE
Feature: Add album artist info

### ISSUE THREAD

**Issue by kooolarpan** [casualsnek/onthespot#86]
Due to the missing album artist, I am unable to filter artists in my local media player.

**Comment by casualsnek** [comment]
Thanks for reporting, the required changes are in https://github.com/casualsnek/onthespot/pull/73 . I will merge it once i have tested it, after that the issue should be fixed. 

If you already have a large collection of media and do not wish to re-download them, i can provide a helper script to fix existing media metadata !

**Comment by kooolarpan** [comment]
Oh, I didn't see the PR. I have already fixed my metadata. Thanks.
